import time
from typing import Dict, Optional, Any, TYPE_CHECKING
import asyncio
import json
import os
import copy
import uuid
from pathlib import Path
from pydantic import model_validator
from app.meta_agent_tool.tool_collection import ToolCollection
from app.llm import LLM
from app.schema import Field, ToolCall, Memory, Message, ToolChoice
from app.config import config
from app.meta_agent_tool.terminate import Terminate
from app.meta_agent_tool.base import BaseTool, ToolResult
try:
    from app.meta_agent.tools.tool_librarian import ToolLibrarian, get_tool_class
    _TOOL_LIBRARIAN_AVAILABLE = True
except ImportError:
    ToolLibrarian = None  # type: ignore
    get_tool_class = None  # type: ignore[assignment]
    _TOOL_LIBRARIAN_AVAILABLE = False
from app.meta_agent.core.schemas import WorkflowHistoryItem
from app.agent.toolcall_toolcosmos import ToolCallToolCosmosAgent
from app.meta_agent_tool.temp_variable_pool import TempVariableViewTool, TEMP_VARIABLE_POOL
from app.meta_agent.executors.code_executor import SandboxTool
from app.meta_agent.workflows.workflow_executor_error_reporter import (
    WorkflowSuccessReporter,
    WorkflowErrorReporter,
    WorkflowPythonError,
    WorkflowToolInterfaceError,
    WorkflowLogicError,
    WorkflowToolRuntimeError,
    WorkflowUnexpectedOutputError,
    WorkflowTaskPlanningError
)
from app.utils.utils import get_os_code_path
from app.meta_agent.executors.ipython_output_cleaner import IPythonOutputCleaner
# if TYPE_CHECKING:
# from app.meta_agent.clients.frontend_proxy import DifyFrontendProxy
    
class CodeActWorkflowExecutorAgent(ToolCallToolCosmosAgent):
    
    system_prompt: str = """
You are a CodeAct agent designed to solve user queries through excuting a workflow following a given Python code guideline.
Given the query and the workflow, first read through the workflow carefully. Make sure you understand each step and the overall structure.
Then, execute the workflow, all tools that you may need are already imported and created an instance.
When you use a tool according to the workflow, make sure to modify the python code in the format `await tool_instance_name.execute(...)`.
The only tool provided to you is `SandboxTool`, which allows you to execute Python code in a IPython Docker container.
If you make sure nowhere is the complete code according to the workflow guideline, execute it using the SandboxTool.


You are given:
- A user query
- A Python workflow guideline (is just like a guide so when necessary you may need to modify parts of the code to adapt to the tool calling format)
- A terminal_id for the SandboxTool, always use this terminal_id when calling SandboxTool in whole workflow execution steps
- All tools imported information: these tools is not for you to call directly, but have been imported and created an instance in the Python runtime, you can use them in your code according to the workflow guideline.
- If user query includes files that need to be processed, these files have already been uploaded to the container and paths are in the format of `/app/files/file_name`, e.g., `/app/files/document.txt`, you can directly use these paths in your code.

Your task:
Execute the workflow, all tools that you may need are already imported and created an instance.


### IMPORTANT - Execution Result & Error Handling Rules

After executing the workflow, you MUST follow the rules below.

---

## ✅ Success Case

If **all workflow steps execute successfully** and the result satisfies the user query:

1. You MUST return a JSON object **directly in your text response** (NOT as executable code).

The JSON format MUST be:

```json
{
    "status": "success",
    "result": "<final result of the workflow execution>"
}
```

2. After returning the JSON result, you MUST call the `terminate` tool to end execution.

---

## ❌ Error Case

If **any error occurs during workflow execution**, you MUST NOT return a JSON object in your text response.

Instead, you MUST report the error **by calling tools**, following the rules below.

---

## ❗ General Error Reporting Rules (MANDATORY)

When an error happens:

1. **DO NOT return any JSON error object in text**
2. **DO NOT attempt to fix the workflow yourself**
3. **DO NOT continue executing remaining steps**
4. You MUST:
   - First, identify the error category
   - Then, report it using the provided workflow error tools

Each error MUST be reported by:
1. Calling `workflow_error_reporter` (high-level error type)
2. Calling EXACTLY ONE corresponding detailed error tool

After reporting the error via tools, you MUST call the `terminate` tool.

---

## 🧭 Error Categories and Their Meanings

You MUST choose **exactly one** of the following error types.

---

### 1️⃣ `python_syntax_error`

**Meaning**  
The workflow code generated by the builder is not valid Python or cannot be executed.

**Examples**
- SyntaxError / IndentationError
- Undefined variable
- Missing import
- Invalid code structure

**Required Action**
- Call `workflow_error_reporter` with `failure_type="python_syntax_error"`
- Then call `workflow_python_error`

---

### 2️⃣ `tool_interface_error`

**Meaning**  
A tool was called incorrectly, even though the code itself is valid.

**Examples**
- Missing required parameters
- Wrong parameter names or types
- Tool return schema misunderstood

**Required Action**
- Call `workflow_error_reporter` with `failure_type="tool_interface_error"`
- Then call `workflow_tool_interface_error`

---

### 3️⃣ `workflow_logic_error`

**Meaning**  
The workflow structure or execution order is incorrect.

**Examples**
- Using a variable before it is produced
- Missing dependency between steps
- Incorrect conditional or branching logic

**Required Action**
- Call `workflow_error_reporter` with `failure_type="workflow_logic_error"`
- Then call `workflow_logic_error`

---

### 4️⃣ `tool_runtime_error`

**Meaning**  
A tool was called correctly but failed during execution.

**Examples**
- Network timeout
- API rate limit
- External service failure
- File not found

**Required Action**
- Call `workflow_error_reporter` with `failure_type="tool_runtime_error"`
- Then call `workflow_tool_runtime_error`

---

### 5️⃣ `unexpected_tool_output`

**Meaning**  
A tool returned output that violates the builder’s assumptions.

**Examples**
- Empty result when non-empty was assumed
- Output format is valid but semantically unusable
- Missing fields in returned data

**Required Action**
- Call `workflow_error_reporter` with `failure_type="unexpected_tool_output"`
- Then call `workflow_unexpected_output_error`

---

### 6️⃣ `task_planning_error`

**Meaning**  
The workflow executed successfully but failed to satisfy the user’s intent.

**Examples**
- The workflow answers only part of the question
- Required comparison / aggregation / reasoning step is missing
- The final result is irrelevant or incomplete

**Required Action**
- Call `workflow_error_reporter` with `failure_type="task_planning_error"`
- Then call `workflow_task_planning_error`

---

### 7️⃣ `system_error` (UNRECOVERABLE)

**Meaning**  
The failure is outside the responsibility of the builder.

**Examples**
- Execution environment failure
- Core dependencies unavailable
- Permission or infrastructure errors

**Required Action**
- Call `workflow_error_reporter` with `failure_type="system_error"`
- Do NOT call any detailed error tool
- Immediately call `terminate`

---

## ⛔ Forbidden Behaviors (STRICT)

- ❌ Returning error JSON in text
- ❌ Guessing how the builder should fix the issue
- ❌ Retrying execution unless explicitly instructed
- ❌ Reporting multiple error types for a single failure

---

## ✅ Final Reminder

- **Success → return JSON + terminate**
- **Failure → tools only + terminate**
- **Error handling is done exclusively through workflow error tools**


### IMPORTANT - Workflow Execution Guidelines
- All tools have already been imported into the Python runtime.
- Each tool can be used by:
    await tool_instance_name.execute(...) or tool_instance_name.execute(...)
- Because you are continuously executing code in a Docker container using the `SandboxTool`, you must use the provided `terminal_id` when calling the `SandboxTool`.
    format: calling SandboxTool using arguments (terminal_id=given_terminal_id, command=your_python_code)
- The execution environment is IPython, which supports top-level await. You can directly use `await` without wrapping in `async def main()`.
    following is the correct format(just an example):
        ```
        result = await a_test_tool.execute("Hello from test tool!")
        print(result.output)
        ```
- You may need to rewrite parts of the workflow code to adapt to the tool calling format.
- When the workflow contains multiple logical steps, multiple tool calls, or any intermediate states that may be meaningful to the user, you MUST decompose the workflow into multiple semantic execution blocks and run them sequentially using the SandboxTool. Further details are provided below.
- All SandboxTool executions using the same terminal_id share the same IPython execution context. Variables, imports, and in-memory state defined in earlier execution blocks remain available in later blocks, as long as the same terminal_id is used.

An example:
    given_query: "Find the capital of France"
    given_workflow: "await web_search.execute("What is the capital of France?")"

    **Your Thought Process**:
    1.  The guideline uses `web_search` tool, which is pre-loaded.
    2.  The call `await web_search.execute(...)` can be used directly in IPython.
    3.  I will create executable IPython code that directly uses await.
    4.  I will then call `SandboxTool` with the generated code and the provided `terminal_id`.

    **Your modified workflow**:
    ```
    result = await web_search.execute("What is the capital of France?")
    print(result.output)
    ```
    Finally call SandboxTool to execute the code: arguments (terminal_id=given_terminal_id, command=your_python_code)

    
When the workflow contains multiple logical steps, multiple tool calls, or any intermediate states that may be meaningful to the user, you MUST decompose the workflow into multiple semantic execution blocks and run them sequentially using the SandboxTool.
    
    Decomposition rules:
        1. Each block SHOULD represent one clear semantic step (e.g., preparation, environment setup, one tool call, result inspection).
        2. Each block MUST be executed separately via:
        SandboxTool.execute(terminal_id=given_terminal_id, command=block_code)
        3. Do NOT combine multiple semantic steps into a single SandboxTool execution if they can be meaningfully observed step-by-step.
    
    The goal is to present the user with a progressive, step-by-step execution process, rather than a single final aggregated output.
    
    An example:
        - query: "Search for the capital of France, save it to a file, then read the file."
        - an original workflow:
            ```
            result = await web_search.execute("What is the capital of France?")
            await write_file.execute("/app/result.txt", result.output)
            read_result = await file_reader.execute("/app/result.txt")
            print(read_result.output)
            ```
        - a possible decomposition and modified workflow:
            Step1:
                ```
                result = await web_search.execute("What is the capital of France?")
                print(result.output)
                search_result = result.output
                ```
            Step2:
                ```
                await write_file.execute("/app/result.txt", search_result)
                print("Result written to /app/result.txt")
                ```
            Step3:
                ```
                read_result = await file_reader.execute("/app/result.txt")
                print(read_result.output)
                ```
        **Remember to exeucute each step sequentially using the SandboxTool with the given terminal_id.**
"""
    # frontend_proxy: "DifyFrontendProxy" = Field()
    workflow: str = Field(default=None)
    llm: LLM = Field(default_factory=lambda: LLM(config_name='tool_maker'))
    agent: Any = None
    terminal_id: int = Field(default=None)
    available_tools: ToolCollection = Field(default_factory=lambda: ToolCollection(WorkflowErrorReporter(), Terminate()))
    python_syntax_error_tool: WorkflowPythonError = Field(default_factory=lambda: WorkflowPythonError())
    tool_interface_error_tool: WorkflowToolInterfaceError = Field(default_factory=lambda: WorkflowToolInterfaceError())
    workflow_logic_error_tool: WorkflowLogicError = Field(default_factory=lambda: WorkflowLogicError())
    tool_runtime_error_tool: WorkflowToolRuntimeError = Field(default_factory=lambda: WorkflowToolRuntimeError())
    unexpected_tool_output_error_tool: WorkflowUnexpectedOutputError = Field(default_factory=lambda: WorkflowUnexpectedOutputError())
    task_planning_error_tool: WorkflowTaskPlanningError = Field(default_factory=lambda: WorkflowTaskPlanningError())
    report: Dict = None
    cleaner: IPythonOutputCleaner = Field(default_factory=lambda: IPythonOutputCleaner())
    
    async def act(self):
        ret = await super().act()
        # TODO: Change to async
        # await self.frontend_proxy.update_running_node_to_frontend()
        return ret

    async def execute_tool(self, command: ToolCall) -> str:
        if command.function.arguments and command.function.arguments.strip():
            arguments = json.loads(command.function.arguments)
        else:
            arguments = {}

        timeout = '10s内'
        if 'timeout' in arguments:
            timeout = '{}s'.format(arguments['timeout'])
        code = arguments.get("command", "")

        if self.agent is not None:
            self.agent.conversation_history.append(
                {
                    'role': 'assistant',
                    'content': "🛠️ 正在调用工具: `{}` (预计用时{})\n\n**执行代码：**\n\n```python\n{}\n```".format(command.function.name, timeout, code),
                    "character_name": "ToolCosmos"
                }
            )

        if command.function.arguments and command.function.arguments.strip():
            arguments = json.loads(command.function.arguments)
        else:
            arguments = {}
        
        if 'lineno' in arguments:
            new_arguments = copy.deepcopy(arguments)
            new_arguments.pop('lineno')
            command.function.arguments = json.dumps(new_arguments)
        
        ret = await super().execute_tool(command)
        
        # 对于 sandbox_tool，清洗输出后再显示给前端
        if command.function.name == 'sandbox_tool':
            code = arguments.get("command", "")
            cleaned_result_dict = await self.cleaner.clean_output(ret, code)
            output = cleaned_result_dict.get("output", "No output")
            summary = cleaned_result_dict.get("summary", "No summary")
            error_info = cleaned_result_dict.get("error_info", None)
            is_error = cleaned_result_dict.get("has_error", False)
            cleaned_result = json.dumps(cleaned_result_dict, ensure_ascii=False, indent=2)
            if is_error:
                error_output = f"**代码运行输出结果：**\n\n```text\n{output}\n```\n\n  **错误信息：**\n\n```text\n{error_info}\n```\n\n  **总结：**\n\n```text\n{summary}\n```\n\n"
                if self.agent is not None:
                    self.agent.conversation_history.append(
                        {
                            'role': 'assistant',
                            'content': "{} 工具 `{}` 调用完成\n\n {}".format(
                                "❌",
                                'sandbox_tool',
                                error_output
                            ),
                            "character_name": "Tool"
                        }
                    )
            else:
                correct_output = f"**代码运行输出结果：**\n\n```text\n{output}\n```\n\n  **总结：**\n\n```text\n{summary}\n```\n\n"
                if self.agent is not None:
                    self.agent.conversation_history.append(
                        {
                            'role': 'assistant',
                            'content': "{} 工具 `{}` 调用完成\n\n {}".format(
                                '✅',
                                'sandbox_tool',
                                correct_output
                            ),
                            "character_name": "Tool"
                        }
                    )
            ret = cleaned_result
        else:
            if self.agent is not None:
                self.agent.conversation_history.append(
                    {
                        'role': 'assistant',
                        'content': "{} 工具 `{}` 调用完成，结果: \n{}".format(
                            "❌" if ret.startswith('Error:') else '✅',
                            command.function.name,
                            ret
                        ),
                        "character_name": "Tool"
                    }
                )
        command.function.arguments = arguments
        return ret
    
    async def handle_workflow_error_reporter(self, command: ToolCall) -> BaseTool:
        try:
            arguments = json.loads(command.function.arguments)
        except Exception as e:
            self.logger_instance.error(f"Failed to parse arguments for WorkflowErrorReporter: {command.function.arguments}, error: {e}")
            return {'result': f"Error: Failed to parse arguments for WorkflowErrorReporter: {command.function.arguments}, error: {e}", 'skip': True}
    
        self.memory.add_message(Message.from_tool_calls([command]))
        self.memory.add_message(Message.tool_message(
            content="Call specific error reporter tool according to failure_type.",
            tool_call_id=command.id,
            name=command.function.name,
        ))
        failure_type = arguments['failure_type']
        error_reporter_tool_map: Dict[str, BaseTool] = {
            'python_syntax_error': self.python_syntax_error_tool,
            'tool_interface_error': self.tool_interface_error_tool,
            'workflow_logic_error': self.workflow_logic_error_tool,
            'tool_runtime_error': self.tool_runtime_error_tool,
            'unexpected_tool_output': self.unexpected_tool_output_error_tool,
            'task_planning_error': self.task_planning_error_tool
        }
        error_reporter = error_reporter_tool_map[failure_type]
        response = await self.llm.ask_tool(
            messages=self.messages,
            system_msgs=(
                [Message.system_message(self.system_prompt)]
                if self.system_prompt
                else None
            ),
            timeout=10,
            tools=[error_reporter],
            tool_choice=ToolChoice.REQUIRED,
        )

        assert len(response.tool_calls) == 1
        original_command = command
        command = response.tool_calls[0]
        self.memory.add_message(Message.from_tool_calls(response.tool_calls))
        # self.cached_messages.append(self.messages[-1])
        self.logger_instance.info(f"🎯 Tool '{error_reporter.name}' completed its mission! Result: {command.function.arguments}")
        # Generate call in the specific schema of that scope type
        tool_args = json.loads(command.function.arguments or "{}")
        tool_call_id = command.id
        
        result = await error_reporter.execute(**tool_args)
        try:
            self.report = json.loads(result.output)
        except Exception as e:
            self.logger_instance.error(f"Failed to parse output of {error_reporter.name}: {result.output}, error: {e}")
            result = f"Error: Failed to parse output of {error_reporter.name}: {result.output}, error: {e}"
        
        self.memory.add_message(Message.tool_message(
            content=result,
            tool_call_id=tool_call_id,
            name=command.function.name,
        ))
        # Hack to terminate after reporting error
        original_command.function.name = Terminate.model_fields['name'].default
        original_command.function.arguments = json.dumps({"status": "failure"})
        return {'result': result, 'skip': True}

    async def handle_workflow_success_reporter(self, command: ToolCall) -> BaseTool:
        try:
            arguments = json.loads(command.function.arguments)
        except Exception as e:
            self.logger_instance.error(f"Failed to parse arguments for WorkflowSuccessReporter: {command.function.arguments}, error: {e}")
            return {'result': f"Error: Failed to parse arguments for WorkflowSuccessReporter: {command.function.arguments}, error: {e}", 'skip': True}
        self.memory.add_message(Message.from_tool_calls([command]))
        self.memory.add_message(Message.tool_message(
            content=ToolResult(output="success"),
            tool_call_id=command.id,
            name=command.function.name,
        ))
    
        result = arguments
        self.logger_instance.info(f"🎯 Workflow executed successfully! Result: {result}")
        # Generate a final guideline revision based on execution experience
        self.memory.add_message(Message.user_message(
            content="""
Based on your real execution experience (actual tool behavior, data flow, and failure avoidance),
you MUST revise the original Python guideline and return a NEW executable Python guideline.

The revised guideline MUST:
1. Be fully executable Python code.
2. Preserve the original task intent and final result.
3. Incorporate improvements discovered during execution (e.g., ordering, validation, retries, assumptions).
4. Remove incidental, one-off fixes that are not generally applicable.
5. Be expressed as a WORKFLOW, not a one-time program:
   - steps must be modular
   - dependencies must be explicit
   - control flow must be reusable
6. Be sufficiently abstract so it can be reused for similar future queries, not only this specific input.

Do NOT describe the changes in natural language.
Do NOT include execution results.
ONLY return the final revised Python guideline enclosed in triple backticks.

Your code:
"""
        ))

        response = await self.llm.ask(
            messages=self.messages,
            system_msgs=(
                [Message.system_message(self.system_prompt)]
                if self.system_prompt
                else None
            ),
            timeout=10,
        )
        self.memory.add_message(Message.assistant_message(content=response))
        code = response.strip().split('\n')
        if '```' in code[0]:
            code = code[1:-1]

        result['revised_workflow'] = '\n'.join(code)
        self.logger_instance.info(f"🛠️ Revised workflow: \n{result['revised_workflow']}")

        self.report = result
        
        # Hack to terminate after reporting success
        command.function.name = Terminate.model_fields['name'].default
        command.function.arguments = json.dumps({"status": "success"})
        return {'result': result, 'skip': True}

    @model_validator(mode='after')
    def set_handle(self):
        self.intervene_handles = {
            WorkflowErrorReporter.model_fields['name'].default: self.handle_workflow_error_reporter,
            WorkflowSuccessReporter.model_fields['name'].default: self.handle_workflow_success_reporter,
        }
        return self

class WorkflowExecutor(BaseTool):
    name: str = 'workflow_executor'
    description: str = "Execute workflow with given tools to solve user's query"
    tool_librarian: Optional[Any] = Field(
        default_factory=(lambda: ToolLibrarian() if _TOOL_LIBRARIAN_AVAILABLE else None)
    )
    executor_agent: CodeActWorkflowExecutorAgent = Field(default=None)
    # frontend_proxy: "DifyFrontendProxy" = Field()
    code_executor: SandboxTool = Field(default_factory=SandboxTool)
    agent: Any = None
    tool_infos: list = []

    async def _build_preload_code(self, tools) -> str:
        lines = ["""
%autoindent False
import importlib.util
import inspect
import asyncio
"""]
        for tool in tools:
            tool_class_name = tool["name"]
            try:
                tool = self.tool_librarian.find_by_name(tool_class_name, match_mode='exact_match')[0]
                # import pdb; pdb.set_trace()
                tool_path = get_os_code_path(tool.path)
                tool_cls = get_tool_class(tool_path, tool_class_name)()

                tool_path_in_container = os.path.join(config.library_config.container_base_path, config.library_config.tool_code_path, tool.path.strip('/') + '.py')

                tool_name = tool_cls.name
                tool_description = tool_cls.description
                tool_parameters =  tool_cls.parameters
                tool_info = f"""
{tool_class_name}
tool_instance_name: {tool_name}
description: {tool_description}
parameters: {tool_parameters}
"""
                self.tool_infos.append(tool_info)
                lines.append(
f"""
spec = importlib.util.spec_from_file_location("{tool_class_name}", "{tool_path_in_container}")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

for obj in vars(module).values():
    if inspect.isclass(obj) and any(c.__name__.split(".")[-1] == 'BaseTool' for c in obj.__mro__[1:]):
        globals()["{tool_name}"] = obj()
        break

"""
)
                print(f"Preloaded tool {tool_class_name} from {tool_path}, a instance named '{tool_name}' is created.")
            except Exception as e:
                raise RuntimeError(f"Failed to preload tool {tool_class_name}: {e}")
        return "\n".join(lines)

    async def _sync_uploaded_files_to_container(self) -> None:
        session_id = self.agent.session_id if (self.agent is not None and hasattr(self.agent, "session_id")) else None
        if not session_id:
            return

        workspace_root = Path(config.workspace_root)
        local_session_dir = workspace_root / f"api_session_{session_id}"
        container_session_dir = f"/app/files"

        if not local_session_dir.exists() or not local_session_dir.is_dir():
            return

        try:
            for local_file in local_session_dir.iterdir():
                if local_file.is_file():
                    try:
                        container_file_path = f"{container_session_dir}/{local_file.name}"      
                        await self.code_executor.copy_to(str(local_file), container_file_path)                       
                        print(f"Synced file: {str(local_file)} -> {container_file_path}")
                    except Exception as file_e:
                            print(f"Failed to sync file {str(local_file)}: {file_e}")
        except Exception as e:
                print(f"Error during file sync process: {str(e)}")
    
    async def execute(self, query, workflow, tools, executor_history: Optional[Memory] = None, marco_history: list[WorkflowHistoryItem] = None):
        preload_code = await self._build_preload_code(tools)
        await self.code_executor.initialize_session(image="my-python-image:latest")
        await self._sync_uploaded_files_to_container()
        terminal_id = await self.code_executor.create_terminal()
        available_tools = ToolCollection(self.code_executor)
        preload_result = await self.code_executor.execute(terminal_id=terminal_id, command=preload_code)
        self.executor_agent = CodeActWorkflowExecutorAgent(
            logger_instance=self.logger_instance, 
            workflow=workflow,
            # frontend_proxy=self.frontend_proxy,
            agent=self.agent,
            terminal_id=terminal_id
        )
        self.executor_agent.available_tools.merge_collection(available_tools)
        self.executor_agent = CodeActWorkflowExecutorAgent.model_validate(self.executor_agent)
        
        if marco_history:
            prompt = """
Previous queries:

{previous_queries}

Last query:
{last_query}

Last guideline:
{last_guideline}

Current query:
{current_query}

Current guideline:
{current_guideline}

terminal_id: 

{terminal_id}

All tools imported information:

{tool_infos}

Solve the above query according to the modified python workflow guideline. 

** Important Notes **

* You have all your execution context kept in the terminal. It is highly recommended that you reuse previous defined variables and imports. 

* When you call SandboxTool to execute workflow, you must use the given terminal_id.

""".format(
    previous_queries = '\n\n'.join([x.query for x in marco_history]),
    last_query = marco_history[-1].query,
    last_guideline = marco_history[-1].guideline,
    current_query = query,
    current_guideline = workflow,
    terminal_id = terminal_id,
    tool_infos = str('\n'.join(self.tool_infos))
)
        else:
            prompt = f"""
Query:

{query}

Guideline:
        
{workflow}

terminal_id: 

{terminal_id}

All tools imported information:

{str('\n'.join(self.tool_infos))}

Solve the above query according to the python workflow guideline. All tools have already been imported. When you call SandboxTool to execute workflow, you must use the given terminal_id.
"""
        if executor_history:
            prompt = None
            if isinstance(executor_history, Memory):
                self.executor_agent.memory = executor_history
            else:
                raise NotImplementedError
        else:
            self.executor_agent.memory.clear()
        await self.executor_agent.run(prompt)
        
        # 从 agent 的 memory 中查找包含 JSON 结果的 assistant 消息
        # 优先查找包含 status 字段的 JSON
        result_dict = None
        last_message = None
        
        if self.executor_agent.report:
            result_dict = self.executor_agent.report
        else:
            import re
            for msg in reversed(self.executor_agent.memory.messages):
                if msg.role == 'assistant' and msg.content:
                    last_message = msg.content
                    
                    # 尝试直接解析整个消息为 JSON
                    try:
                        parsed = json.loads(msg.content.strip())
                        if isinstance(parsed, dict) and 'status' in parsed:
                            result_dict = parsed
                            break
                    except json.JSONDecodeError:
                        pass
                    
                    # 尝试从文本中提取 JSON 对象
                    # 使用更精确的正则，匹配包含 "status" 字段的 JSON
                    json_pattern = r'\{[^{}]*"status"[^{}]*\}|\{(?:[^{}]|\{[^{}]*\})*"status"(?:[^{}]|\{[^{}]*\})*\}'
                    json_matches = re.findall(json_pattern, msg.content, re.DOTALL)
                    
                    for json_str in json_matches:
                        try:
                            parsed = json.loads(json_str)
                            if isinstance(parsed, dict) and 'status' in parsed:
                                result_dict = parsed
                                break
                        except json.JSONDecodeError:
                            continue
                    
                    if result_dict:
                        break
        
        if result_dict:
            return ToolResult(output=json.dumps(result_dict, ensure_ascii=False))
        else:
            return ToolResult(output=last_message or "No result")

    def get_memory(self):
        return self.executor_agent.memory


async def test_workflow_executor_initialization():
    executor = WorkflowExecutor(tool_librarian=ToolLibrarian(), code_executor=SandboxTool(terminal_start_commands=[
        "bash -c 'stty -echo; ipython'",
    ]))
    # await executor.execute('What is the capital of France?', 'await web_search.execute("What is the capital of France?")', [
    #     {'name': 'DockerCodeExecutorTool'}, 
    #     {'name': 'WebSearch', 'arguments': {'query': '123'}}
    # ])
    test_result = await executor.execute('What is the capital of France?', 'await web_search.execute("What is the capital of France?")', [
        {'name': 'WebSearch'}
    ])
    # test_result = await executor.execute('/app/test_file.txt中有一个问题，调用工具获取问题并解答', 'await question = a_file_test_tool.execute("/app/test_file.txt")  await web_search.execute(question)', [
    #     {'name': 'WebSearch'},
    #     {'name': 'AFileTestTool'}
    # ])
    print("*********--*************************************************************")
    print(test_result)
    print("*********--*************************************************************")

if __name__ == '__main__':
    asyncio.run(test_workflow_executor_initialization())