from typing import Optional
from demo_trace import AgentTrace

class SimplePipelineResult:
    def __init__(self, query: str, new_code: Optional[str] = None):
        self.query = query
        self.new_code = new_code


def run_demo(trace: AgentTrace) -> SimplePipelineResult:
    """Run a minimal pipeline on the provided AgentTrace and return a new skill code string.

    This stub simulates retrieval -> executor (skipped) -> extractor -> tester -> commit.
    """
    print('\n[Phase] Executor (prebuilt trace)')
    print(f'  Query: {trace.query}')
    print(f'  Steps: {len(trace.steps)}')
    for i, s in enumerate(trace.steps, 1):
        print(f'    Step {i}: {s.thought} (tool={s.tool_call})')
        if s.code_block:
            print('      Code block:\n' + s.code_block)

    # Stub extractor: produce a simple function that returns dict for a transcript line
    new_code = """def parse_transcript_line(line: str) -> dict:\n    # Minimal parser produced by extractor (demo)\n    parts = [p.strip() for p in line.replace(';', '').split()]\n    return {'name': parts[1], 'score': int(parts[3])}\n"""

    print('\n[Phase] Extractor')
    print('  Produced new skill code (preview):')
    for ln in new_code.splitlines():
        print('    ' + ln)

    # Stub tester: run a simple local check
    print('\n[Phase] Tester')
    sample = "Name: Alice; Score: 90;"
    try:
        locals_dict = {}
        exec(new_code, {}, locals_dict)
        parsed = locals_dict['parse_transcript_line'](sample)
        print('  Tester sample parse ->', parsed)
        tester_ok = True
    except Exception as e:
        print('  Tester failed:', e)
        tester_ok = False

    # Commit (stub): write to a local file
    if tester_ok:
        out_path = 'evolved_skill.py'
        with open(out_path, 'w') as f:
            f.write('# Evolved skill (auto-generated by SimplePipeline)\n')
            f.write(new_code)
        print(f"\n[Phase] Commit: wrote evolved skill to {out_path}")
    else:
        print('\n[Phase] Commit: skipped due to tester failure')

    return SimplePipelineResult(query=trace.query, new_code=new_code if tester_ok else None)
