"""
test_multiturn_debug.py — 多轮 same-query debug 测试

目标:
  1. 展示每个 LLM 调用的完整输入输出（Planner / Gardener / Gardener 内部子调用）
  2. 识别并修复 visible bugs（参见 KNOWN_BUGS 注释）
  3. 运行 2 轮相同查询、验证 REUSE 逻辑

运行方式:
  cd /home/lixujun/skill_evolving
  LLM_CACHE_ENABLED=1 LLM_BP_ENABLED=1 conda run -n meta-agent \
    python -m pytest app/meta_agent/skills/tests/integration/test_multiturn_debug.py \
    -vs -m llm 2>&1 | tee /tmp/multiturn_debug.log

断点辅助文件:
  /tmp/llm_bp_state.json  — 结构化断点状态（JSON）
  /tmp/llm_bp_ns.py       — 可 exec() 的变量快照（messages/response/state）
  /tmp/llm_debug_log.md   — 每次断点的 Markdown 说明（追加写入，固定路径）
  /tmp/llm_bp_pause       — 存在 → 测试暂停中
  /tmp/llm_bp_resume      — 创建 → 恢复测试
  配套: llm_bp_inspector.py — 自动监听并开启交互 REPL
"""
from __future__ import annotations

import asyncio
import datetime
import json
import logging
import os
import sys
import textwrap
import time
from typing import Any, List, Optional
from unittest.mock import AsyncMock, patch

import pytest

from app.meta_agent.skills.pipeline import (
    PipelineSession,
    PlanningResult,
    ProposedSkill,
    SkillEvolvingPipeline,
)
from app.meta_agent.skills.tests.conftest import create_mock_skill
from app.meta_agent.skills.tests.test_data_integration import (
    SKILL_CODE_INT_B_V1_0,
    TRACE_INT_B_1,
)

# ── Logging setup ──────────────────────────────────────────────────────────────

def _setup_verbose_logging():
    """Configure DEBUG logging to stdout so all LLM prompts / responses are visible."""
    fmt = logging.Formatter(
        "%(asctime)s [%(name)s] %(levelname)s  %(message)s", "%H:%M:%S"
    )
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(fmt)
    for name in ("skill_pipeline", "skill_gardener", "skill_reviewer", "app.llm"):
        lg = logging.getLogger(name)
        lg.setLevel(logging.DEBUG)
        lg.addHandler(handler)
        lg.propagate = False


_setup_verbose_logging()

# ── Breakpoint infrastructure ──────────────────────────────────────────────────

_BP_STATE   = "/tmp/llm_bp_state.json"
_BP_PAUSE   = "/tmp/llm_bp_pause"
_BP_RESUME  = "/tmp/llm_bp_resume"
_BP_ENABLED = os.environ.get("LLM_BP_ENABLED", "0") == "1"
_BP_CALL_COUNT = 0  # global counter, incremented each LLM call


async def _breakpoint_pause(
    label: str,
    messages: list,
    system_msgs: list,
    response: str,
    extra: Optional[dict] = None,
) -> None:
    """Write current LLM call state to file and block until resume signal.

    Only active when LLM_BP_ENABLED=1.
    """
    if not _BP_ENABLED:
        return

    global _BP_CALL_COUNT
    _BP_CALL_COUNT += 1

    def _get(m, key: str, default: str = "") -> str:
        if isinstance(m, dict):
            return m.get(key, default)
        return str(getattr(m, key, default) or default)

    last_user = next(
        (_get(m, "content") for m in reversed(messages) if _get(m, "role") == "user"),
        "",
    )
    tool_history = [
        {"role": _get(m, "role"), "content": _get(m, "content")[:300]}
        for m in messages
        if _get(m, "role") in ("assistant", "tool")
    ][-6:]

    sys_text = "\n".join(_get(m, "content") for m in (system_msgs or []))

    state = {
        "call_number": _BP_CALL_COUNT,
        "label": label,
        "system_text": sys_text[:3000],
        "messages_count": len(messages),
        "last_user_msg": last_user[:2000],
        "recent_tool_history": tool_history,
        "response": response[:4000],
        "extra": extra or {},
    }
    with open(_BP_STATE, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2)

    # ── Write /tmp/llm_bp_ns.py — loadable variable snapshot for pdb/REPL ──
    _write_ns_file(messages, system_msgs, response, extra, state)

    # ── Append to /tmp/llm_debug_log.md ─────────────────────────────────────
    _append_debug_log(state, sys_text, last_user, response)

    open(_BP_PAUSE, "w").close()

    while os.path.exists(_BP_PAUSE) and not os.path.exists(_BP_RESUME):
        await asyncio.sleep(0.3)

    for path in (_BP_PAUSE, _BP_RESUME, _BP_STATE):
        try:
            os.remove(path)
        except FileNotFoundError:
            pass


def _write_ns_file(messages: list, system_msgs: list, response: str, extra: Optional[dict], state: dict) -> None:
    """Write /tmp/llm_bp_ns.py — a Python file that can be exec()'d to load all
    breakpoint variables into a REPL namespace.

    Usage in inspector:  exec(open('/tmp/llm_bp_ns.py').read())
    """
    def _safe_repr(obj) -> str:
        try:
            return repr(obj)
        except Exception:
            return repr(str(obj))

    lines = [
        "# Auto-generated by _breakpoint_pause — exec() this in pdb/IPython to inspect",
        f"# Breakpoint #{state['call_number']}: {state['label']}",
        f"# Generated: {datetime.datetime.now().isoformat()}",
        "",
        f"call_number = {state['call_number']!r}",
        f"label = {state['label']!r}",
        f"messages_count = {state['messages_count']!r}",
        f"response = {response!r}",
        f"extra = {_safe_repr(extra)}",
        f"state = {_safe_repr(state)}",
        "",
        "# messages — raw list (dict or Message objects), may need getattr/[] access",
        f"_messages_repr = {_safe_repr(messages)}",
        "# system_msgs — raw list",
        f"_system_msgs_repr = {_safe_repr(system_msgs)}",
        "",
        "print(f'[ns loaded] BP#{call_number}: {label}')",
        "print(f'  response[:200] = {response[:200]!r}')",
    ]
    try:
        with open("/tmp/llm_bp_ns.py", "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
    except Exception as e:
        print(f"[bp] warning: failed to write ns file: {e}")


def _append_debug_log(state: dict, sys_text: str, last_user: str, response: str) -> None:
    """Append a Markdown section for this breakpoint to /tmp/llm_debug_log.md."""
    ts = datetime.datetime.now().strftime("%H:%M:%S")
    call_no = state["call_number"]
    label = state["label"]
    msgs_count = state["messages_count"]
    tool_hist = state.get("recent_tool_history", [])
    extra = state.get("extra", {})

    section_lines = [
        f"\n---\n",
        f"## 断点 #{call_no} — {label}",
        f"**时间:** {ts}  **消息数:** {msgs_count}",
    ]

    if extra.get("tool_calls_summary"):
        section_lines.append(f"\n**工具调用:** `{extra['tool_calls_summary'][:300]}`")

    if sys_text.strip():
        section_lines += [
            "\n### System Prompt (前500字)",
            "```",
            sys_text.strip()[:500],
            "```",
        ]

    if last_user.strip():
        section_lines += [
            "\n### 最后一条 User 消息 (前800字)",
            "```",
            last_user.strip()[:800],
            "```",
        ]

    if tool_hist:
        section_lines += ["\n### 最近工具调用历史"]
        for h in tool_hist:
            role = h.get("role", "?")
            content = (h.get("content") or "")[:200]
            section_lines.append(f"- **{role}**: {content}")

    section_lines += [
        "\n### LLM 响应 (前1200字)",
        "```",
        response.strip()[:1200],
        "```",
    ]

    log_path = "/tmp/llm_debug_log.md"
    # Write header if file is new or empty
    if not os.path.exists(log_path) or os.path.getsize(log_path) == 0:
        with open(log_path, "w", encoding="utf-8") as f:
            f.write("# LLM Debug Log\n\n_每次断点触发时自动追加_\n")

    try:
        with open(log_path, "a", encoding="utf-8") as f:
            f.write("\n".join(section_lines) + "\n")
    except Exception as e:
        print(f"[bp] warning: failed to write debug log: {e}")


# ── LLM call interceptor ───────────────────────────────────────────────────────

_CALL_LOG: List[dict] = []   # global per-test, reset in setup


def _log_llm_call(label: str, messages: list, system_msgs: list, response: str):
    """Print and record one LLM round-trip.

    messages / system_msgs may be either dicts or Message pydantic objects —
    both are handled transparently.
    """
    def _get(m, key: str, default: str = "") -> str:
        """Universal getter: works for both dict and Message pydantic objects."""
        if isinstance(m, dict):
            return m.get(key, default)
        return str(getattr(m, key, default) or default)

    divider = "=" * 80
    sys_text = "\n".join(_get(m, "content") for m in (system_msgs or []))
    user_text = "\n".join(
        _get(m, "content") for m in messages if _get(m, "role") == "user"
    )
    print(f"\n{divider}")
    print(f"  LLM CALL [{label}]")
    print(f"{divider}")
    print(f"--- SYSTEM ({len(sys_text)} chars) ---")
    print(textwrap.shorten(sys_text, width=600, placeholder=" ...[truncated]"))
    print(f"--- USER MSG ({len(user_text)} chars) ---")
    print(textwrap.shorten(user_text, width=800, placeholder=" ...[truncated]"))
    print(f"--- RESPONSE ({len(response)} chars) ---")
    print(response[:1200] if len(response) > 1200 else response)
    print(divider + "\n")
    _CALL_LOG.append({"label": label, "response": response})


# ── Query / seed data ─────────────────────────────────────────────────────────

QUERY = (
    "Produce a comprehensive grade analysis for scores [75, 82, 91, 68, 77, 95, 60, 88]. "
    "Include mean, median, standard deviation, grade distribution (A/B/C/D/F), "
    "and identify at-risk students (score < 70)."
)
SKILL_NAME = "analyze_student_grades"
SEED_CODE = SKILL_CODE_INT_B_V1_0
PREBUILT_TRACE = TRACE_INT_B_1     # exact same trace for both rounds


# ── Helpers ───────────────────────────────────────────────────────────────────

def _make_pipeline(mock_db) -> SkillEvolvingPipeline:
    p = SkillEvolvingPipeline()
    p.db_manager = mock_db
    return p


async def _retrieval_and_embed(pipeline: SkillEvolvingPipeline, query: str):
    """Run retrieval phase and return (skills, embedding)."""
    ret = await pipeline._phase_retrieval(query, top_k=5, threshold=0.1)
    skills = getattr(ret, "_skills", [])
    embedding = getattr(ret, "query_embedding", None)
    return skills, embedding


# ── Main debug test ────────────────────────────────────────────────────────────

class TestMultiTurnSameQueryDebug:

    @pytest.mark.llm
    @pytest.mark.asyncio
    async def test_round_by_round_with_verbose_output(self, mock_db):
        """
        Two rounds of identical query.

        Round 1:
          - Retrieval phase
          - Planning phase (direct call — bypasses Docker requirement)
          - Extractor phase with prebuilt trace

        Round 2 (same query):
          - Retrieval phase (from fresh session call)
          - Planning phase — expects REUSE or refined plan
          - Extractor phase

        All LLM inputs/outputs are printed to stdout.
        Assertions after each round verify structural correctness.
        """
        _CALL_LOG.clear()
        global _BP_CALL_COUNT
        _BP_CALL_COUNT = 0

        skill = create_mock_skill(mock_db, SKILL_NAME, "1.0", code=SEED_CODE)
        pipeline = _make_pipeline(mock_db)

        # ── Intercept LLM.ask AND LLM.ask_tool to print full I/O ───────────
        # Bug-fix: previously only LLM.ask was patched, which missed all Gardener
        # (ToolCallToolCosmosAgent) calls that go through LLM.ask_tool.
        from app.llm import LLM

        _original_ask = LLM.ask
        _original_ask_tool = LLM.ask_tool

        async def _patched_ask(self_llm, messages, system_msgs=None, **kw):
            resp = await _original_ask(self_llm, messages, system_msgs=system_msgs, **kw)
            _log_llm_call(
                label=f"LLM.ask [{self_llm.model}]",
                messages=messages,
                system_msgs=system_msgs or [],
                response=str(resp),
            )
            await _breakpoint_pause(
                label=f"LLM.ask [{self_llm.model}]",
                messages=messages,
                system_msgs=system_msgs or [],
                response=str(resp),
            )
            return resp

        async def _patched_ask_tool(self_llm, messages, system_msgs=None, tools=None, **kw):
            resp = await _original_ask_tool(
                self_llm, messages, system_msgs=system_msgs, tools=tools, **kw
            )
            tool_calls_summary = ""
            if resp and resp.tool_calls:
                tool_calls_summary = " | ".join(
                    f"{tc.function.name}({tc.function.arguments[:80]})"
                    for tc in resp.tool_calls
                )
            resp_str = f"content={resp.content!r}  tool_calls=[{tool_calls_summary}]" if resp else "(None)"
            _log_llm_call(
                label=f"LLM.ask_tool [{self_llm.model}]",
                messages=messages,
                system_msgs=system_msgs or [],
                response=resp_str,
            )
            await _breakpoint_pause(
                label=f"LLM.ask_tool [{self_llm.model}]",
                messages=messages,
                system_msgs=system_msgs or [],
                response=resp_str,
                extra={"tool_calls_summary": tool_calls_summary},
            )
            return resp

        def _patch_ctx():
            """Context manager: patch both ask and ask_tool simultaneously."""
            return (
                patch.object(LLM, "ask", _patched_ask),
                patch.object(LLM, "ask_tool", _patched_ask_tool),
            )

        # ═══════════════════════════════════════════════════════════════════
        # ROUND 1
        # Bug-fix: previously _run_planning_phase was called explicitly here AND
        # again inside run_with_session → _run_phases (double planning).
        # Now planning runs exactly once (inside run_with_session) and the result
        # is read back from result_r1.planning_result.
        # ═══════════════════════════════════════════════════════════════════
        print("\n" + "#" * 80)
        print("# ROUND 1 — fresh run (no prior history)")
        print("#" * 80)

        session = PipelineSession(session_id="debug-r1", db_manager=mock_db)

        ask_ctx, ask_tool_ctx = _patch_ctx()
        with ask_ctx, ask_tool_ctx:
            # --- Phase 0: Retrieval (shown for context) ---
            print("\n>>> Phase 0: Retrieval")
            retrieved_skills, query_embedding = await _retrieval_and_embed(pipeline, QUERY)
            print(f"    retrieved {len(retrieved_skills)} skills  "
                  f"embedding={'yes' if query_embedding else 'NO'}")

            # --- Phase 0.5 + 2+3: Full pipeline (Planning internally + Extractor) ---
            print("\n>>> Phase 0.5+2+3: run_with_session (Planning + Extractor, prebuilt trace)")
            result_r1 = await pipeline.run_with_session(
                session=session,
                query=QUERY,
                skill_name=SKILL_NAME,
                skill_id=skill.id,
                prebuilt_trace=TRACE_INT_B_1,
                skip_tester=True,
            )

        # Planning result is now readable from result.planning_result
        planning_r1 = result_r1.planning_result
        _print_planning_result(planning_r1, round_num=1)
        _print_pipeline_result(result_r1, round_num=1)

        # Round 1 assertions
        assert result_r1.extractor.ok, f"Round 1 extractor failed: {result_r1.extractor.error}"
        print(f"\n✓ Round 1: extractor.ok={result_r1.extractor.ok}  "
              f"new_skill_id={result_r1.new_skill_id}")

        # ═══════════════════════════════════════════════════════════════════
        # ROUND 2  (identical query — exercise REUSE / refinement path)
        # ═══════════════════════════════════════════════════════════════════
        print("\n" + "#" * 80)
        print("# ROUND 2 — same query (should trigger REUSE or targeted refinement)")
        print("#" * 80)

        ask_ctx2, ask_tool_ctx2 = _patch_ctx()
        with ask_ctx2, ask_tool_ctx2:
            print("\n>>> Phase 0.5+2+3: run_with_session round 2 (prebuilt trace)")
            result_r2 = await pipeline.run_with_session(
                session=session,
                query=QUERY,
                skill_name=SKILL_NAME,
                skill_id=skill.id,
                prebuilt_trace=TRACE_INT_B_1,
                skip_tester=True,
            )

        _print_pipeline_result(result_r2, round_num=2)
        planning_r2 = result_r2.planning_result
        _print_planning_result(planning_r2, round_num=2)
        assert result_r2.extractor.ok, f"Round 2 extractor failed: {result_r2.extractor.error}"
        print(f"\n✓ Round 2: extractor.ok={result_r2.extractor.ok}  "
              f"new_skill_id={result_r2.new_skill_id}")

        # ═══════════════════════════════════════════════════════════════════
        # Summary
        # ═══════════════════════════════════════════════════════════════════
        print("\n" + "=" * 80)
        print("SUMMARY")
        print("=" * 80)
        print(f"Total LLM calls captured: {len(_CALL_LOG)}")
        for i, entry in enumerate(_CALL_LOG, 1):
            print(f"  [{i}] {entry['label']}  response_len={len(entry['response'])}")

        print(f"\nSession rounds: {session.round_count}")
        print(f"Session evolved_skill_ids: {session.evolved_skill_ids}")

        # Multi-turn sanity
        assert session.round_count == 2, "Session should have 2 rounds accumulated"
        assert len(session.query_history) == 2

        # After 2 rounds, planning_r2 should either be REUSE path or produce a plan
        if planning_r2 is not None:
            print(f"\nRound 2 plan length: {len(planning_r2.workflow_plan)} chars")
            print(f"Round 2 proposed_skills: {[ps.name for ps in planning_r2.proposed_skills]}")
        else:
            print("\nWARNING: Round 2 planning returned None (planning phase failed silently)")

    # ── Planning-only standalone test (no Docker, no Extractor) ────────────

    @pytest.mark.llm
    @pytest.mark.asyncio
    async def test_planning_phase_standalone(self, mock_db):
        """
        Exercise _run_planning_phase in isolation: 3 rounds of same query.

        Round 1: no history → expect full plan + optional proposed_skills
        Round 2: session has round 1 → planner sees previous plan → may say REUSE
        Round 3: same → stronger REUSE signal

        This test does NOT need Docker or a Gardener.
        """
        _CALL_LOG.clear()
        create_mock_skill(mock_db, SKILL_NAME, "1.0", code=SEED_CODE)
        pipeline = _make_pipeline(mock_db)

        from app.llm import LLM
        _original_ask = LLM.ask

        async def _patched_ask(self_llm, messages, system_msgs=None, **kw):
            resp = await _original_ask(self_llm, messages, system_msgs=system_msgs, **kw)
            _log_llm_call(
                label=f"LLM.ask [{self_llm.model}]",
                messages=messages,
                system_msgs=system_msgs or [],
                response=str(resp),
            )
            return resp

        # Build a fake session with an existing round result to inject cross-round history.
        from app.meta_agent.skills.pipeline import PipelineResult, PhaseResult
        from app.meta_agent.skills.schemas import AgentTrace, TraceFormat

        session = PipelineSession(session_id="plan-only-debug", db_manager=mock_db)

        retrieved_skills, query_embedding = await _retrieval_and_embed(pipeline, QUERY)
        print(f"\n[retrieval] {len(retrieved_skills)} skills, "
              f"embedding_dim={len(query_embedding) if query_embedding else 0}")

        with patch.object(LLM, "ask", _patched_ask):
            for round_num in range(1, 4):
                print(f"\n{'#'*60}")
                print(f"# Planning — Round {round_num}")
                print(f"{'#'*60}")

                pr = await pipeline._run_planning_phase(
                    query=QUERY,
                    retrieved_skills=retrieved_skills,
                    session=session,
                    query_embedding=query_embedding,
                )
                _print_planning_result(pr, round_num=round_num)

                # Simulate a round result on the session so Round 2/3 see history
                if pr is not None:
                    fake_trace = AgentTrace(
                        query=QUERY,
                        trace_format=TraceFormat.REACT,
                        steps=[],
                        final_answer="(simulated)",
                        involved_skills=[],
                    )
                    fake_trace.workflow_plan = pr.workflow_plan
                    fake_result = PipelineResult(query=QUERY)
                    fake_result.execution_trace = fake_trace
                    fake_result.tester = PhaseResult(ok=True, elapsed_s=0.0)
                    fake_result.new_skill_id = None
                    session.query_history.append(QUERY)
                    session.traces.append(fake_trace)
                    session.round_results.append(fake_result)

        print(f"\nTotal LLM calls in planning-only test: {len(_CALL_LOG)}")
        assert len(_CALL_LOG) > 0, "Should have made at least 1 LLM call"


# ── Pretty-printers ────────────────────────────────────────────────────────────

def _print_planning_result(pr: Optional[PlanningResult], round_num: int):
    sep = "-" * 60
    print(f"\n{sep}")
    print(f"  Planning Result — Round {round_num}")
    print(sep)
    if pr is None:
        print("  [NONE — planning phase returned None]")
        return
    print(f"  workflow_plan ({len(pr.workflow_plan)} chars):")
    print(textwrap.indent(pr.workflow_plan[:800], "    "))
    if pr.proposed_skills:
        print(f"\n  proposed_skills ({len(pr.proposed_skills)} total):")
        for ps in pr.proposed_skills:
            print(f"    - {ps.name}: {ps.description[:80]}")
            print(f"      source: {ps.source_query[:60]!r}")
            print(textwrap.indent(ps.code_fragment[:200], "      "))
    else:
        print("  proposed_skills: [] (none extracted)")
    print(sep)


def _print_pipeline_result(result, round_num: int):
    sep = "-" * 60
    print(f"\n{sep}")
    print(f"  Pipeline Result — Round {round_num}")
    print(sep)
    phases = [
        ("retrieval", result.retrieval),
        ("executor",  result.executor),
        ("extractor", result.extractor),
        ("tester",    result.tester),
        ("commit",    result.commit),
    ]
    for name, ph in phases:
        status = "✓" if ph.ok else "✗"
        print(f"  {status} {name:<12} {ph.elapsed_s:.1f}s  "
              f"detail={ph.detail[:60]!r}  err={ph.error[:40]!r}")
    print(f"  new_skill_id: {result.new_skill_id}")
    code_len = len(result.new_skill_code) if result.new_skill_code else 0
    print(f"  new_skill_code: {code_len} chars")
    print(sep)
